AY2324S2-CS2103T-F12-2/tp

- docs/DeveloperGuide.md
> Add use case for find article command

- docs/AboutUs.md
Assign roles and responsibilities of team members in AboutUs
> Update roles in AboutUs

- src/main/java/seedu/address/model/ArticleBook.java
- src/main/java/seedu/address/model/ReadOnlyArticleBook.java
- src/main/java/seedu/address/model/article/Article.java
- src/main/java/seedu/address/model/article/UniqueArticleList.java
Article classes are seperate from Person classes.
Article class, and an ArticleBook is also created in order to save article in a different addressbook from existing addressbook.
Doing so allows us to have more features related to articles compared to saving articles as an attribute to a person.
> Add Article classes

- docs/UserGuide.md
- src/main/java/seedu/address/model/util/SampleArticleDataUtil.java
- src/main/java/seedu/address/storage/StorageManager.java
Changes include adding a Description for the find article command in the User Guide on top of some minor bug fixes.
Closes #38
> Add find article command description to User Guide

- docs/AboutUs.md
- docs/UserGuide.md
add list articles command to user guide
> Update user guide to include list articles

- src/main/java/seedu/address/logic/commands/articlecommands/SortArticleCommand.java
- src/main/java/seedu/address/logic/parser/ArticleBookParser.java
- src/main/java/seedu/address/logic/parser/SortArticleCommandParser.java
> Add support for parsing sort article command

- src/main/java/seedu/address/logic/commands/articlecommands/SortArticleCommand.java
- src/main/java/seedu/address/model/ArticleBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/article/UniqueArticleList.java
- src/main/java/seedu/address/model/util/SampleArticleDataUtil.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
Closes #58 
Merge this PR after #57 is merged and closed.
> Implement the sort article command

- src/main/java/seedu/address/model/ModelManager.java
> Fix minor bugs in ModelManager.java

- src/main/java/seedu/address/logic/parser/EditArticleCommandParser.java
> Minor bug fix for incorrect article tag prefix

- src/main/java/seedu/address/logic/commands/articlecommands/EditArticleCommand.java
- src/main/java/seedu/address/logic/parser/AddArticleCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/EditArticleCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/article/Article.java
- src/main/java/seedu/address/model/article/Outlet.java
- src/main/java/seedu/address/model/util/SampleArticleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedArticle.java
- src/main/java/seedu/address/storage/JsonAdaptedOutlet.java
- src/main/java/seedu/address/storage/StorageManager.java
- src/main/java/seedu/address/ui/ArticleCard.java
- src/main/resources/view/ArticleListCard.fxml
- src/main/resources/view/DarkTheme.css
> Implement Outlet article attribute as class

- docs/DeveloperGuide.md
- docs/diagrams/LinkClassDiagram.puml
Edit developer guide to contain information about the link feature that is going to be added for users to have an idea of proposed features that are coming up.
> Edit Developer Guide

- src/main/resources/view/DarkTheme.css
> Edited css for readability

- src/main/java/seedu/address/logic/commands/articlecommands/EditArticleCommand.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/articlecommands/ArticleCommandTestUtil.java
- src/test/java/seedu/address/testutil/ArticleBookBuilder.java
- src/test/java/seedu/address/testutil/ArticleBuilder.java
- src/test/java/seedu/address/testutil/EditArticleDescriptorBuilder.java
- src/test/java/seedu/address/testutil/TypicalArticles.java
> Add test util classes for articles

- src/main/java/seedu/address/logic/commands/SetCommand.java
- src/main/java/seedu/address/logic/commands/articlecommands/FilterArticleCommand.java
- src/main/java/seedu/address/logic/commands/articlecommands/RemoveArticleFilterCommand.java
- src/main/java/seedu/address/logic/parser/ArticleBookParser.java
- src/main/java/seedu/address/logic/parser/FilterArticleCommandParser.java
- src/main/java/seedu/address/model/article/ArticleMatchesStatusPredicate.java
- Change success and failure messages to be more informative.
- Add new rmfilter command to clear filters.
- Change some code to use ParserUtil instead of parsing on its own.
- Remove SetCommand
> Branch kk fix feature flaws

- src/main/java/seedu/address/ui/ArticleCard.java
- src/main/resources/view/ArticleListCard.fxml
> Implement dynamic UI spacing

- src/main/java/seedu/address/Main.java
- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/articlecommands/EditArticleCommand.java
- src/main/java/seedu/address/logic/parser/AddArticleCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/article/Article.java
- src/main/java/seedu/address/model/article/Link.java
- src/main/java/seedu/address/model/util/SampleArticleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedArticle.java
- src/main/java/seedu/address/ui/ArticleCard.java
- src/main/resources/view/ArticleListCard.fxml
- src/test/java/seedu/address/logic/commands/articlecommands/ArticleCommandTestUtil.java
- src/test/java/seedu/address/testutil/ArticleBuilder.java
- src/test/java/seedu/address/testutil/EditArticleDescriptorBuilder.java
- src/test/java/seedu/address/testutil/TypicalArticles.java
Link feature is added, which opens up the webpage of the article that is published.
> Add Link feature

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/articlecommands/AddArticleCommand.java
- src/main/java/seedu/address/logic/commands/articlecommands/EditArticleCommand.java
Additionally, the error messages for Adding and Editing Articles is also updated
> Add Lookup Features to UG

- src/main/java/seedu/address/logic/parser/SortArticleCommandParser.java
- src/main/java/seedu/address/logic/parser/SortCommandParser.java
- src/main/java/seedu/address/model/article/UniqueArticleList.java
- src/main/java/seedu/address/model/person/UniquePersonList.java
> Fix case-sensitivity bug for sort commands

- docs/DeveloperGuide.md
- docs/diagrams/SortArticlesSequenceDiagram-Logic.puml
- docs/diagrams/SortArticlesSequenceDiagram-Model.puml
- docs/diagrams/SortPersonsSequenceDiagram-Logic.puml
Changes include:
* Change title from `AB-3` to `PressPlanner`
* Add description for sort article command
* Add user stories to the corresponding table
* Delete certain extensions in use case which does not follow current program behavior
* Add an entry to planned enhancements regarding sort commands
* Add more use cases and standardize their ordering
Closes #215 
Closes #145 
Closes #228
> Making bug fixes and additions to the DG

- src/main/java/seedu/address/logic/parser/AddArticleCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
> Bug fix for allowing invalid dates as input

- docs/UserGuide.md
Added warning to add article about the use of empty headlines.
Fixes #147
> Add empty headline warning to UG

- docs/DeveloperGuide.md
- docs/diagrams/FilterSequenceDiagram.puml
- docs/diagrams/LogicClassDiagram.puml
- docs/diagrams/ModelFilterClassDiagram.puml
Update diagram sizes.
Add article command info to
LogicClassDiagram.
> Fix uml diagrams

- docs/DeveloperGuide.md
For Add and Delete Article
Additionally, Added acknowledgements
> Add manual tests in DG

- docs/DeveloperGuide.md
- docs/diagrams/style2.puml
> Reduce font size for Model Class diagram

- docs/DeveloperGuide.md
> Finalize the DG by adding and organizing info
